-- DDL --

-- CREATE 

CREATE TABLE students (
	id SERIAL PRIMARY KEY, 
	name VARCHAR NOT NULL,
	phone VARCHAR(10),
	email VARCHAR UNIQUE
);

CREATE TABLE employees (
	id SERIAL PRIMARY KEY,
	name VARCHAR NOT NULL,
	position VARCHAR(50) NOT NULL,
	salary DECIMAL(10, 2),
	isActive BOOLEAN DEFAULT true,
	hire_date DATE DEFAULT CURRENT_DATE
);
