CREATE TABLE IF NOT EXISTS customers (
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name TEXT NOT NULL,
	email TEXT UNIQUE NOT NULL,
	registration_date DATE DEFAULT CURRENT_DATE
);


CREATE TABLE IF NOT EXISTS products (
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	name VARCHAR NOT NULL,
	price NUMERIC(10, 2) NOT NULL,
	stock INT NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	customer_id BIGINT REFERENCES customers (id),
	order_date DATE NOT NULL
);

CREATE TABLE order_details (
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	order_id BIGINT REFERENCES orders (id),
	product_id BIGINT REFERENCES products (id),
	quantity INT NOT NULL,
	unit_price NUMERIC(10, 2) NOT NULL
);